// Code generated by "stringer -type=LockState"; DO NOT EDIT.

package sessions

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Locked-0]
	_ = x[Unlocked-1]
	_ = x[Unknown-4294967295]
}

const (
	_LockState_name_0 = "LockedUnlocked"
	_LockState_name_1 = "Unknown"
)

var (
	_LockState_index_0 = [...]uint8{0, 6, 14}
)

func (i LockState) String() string {
	switch {
	case i <= 1:
		return _LockState_name_0[_LockState_index_0[i]:_LockState_index_0[i+1]]
	case i == 4294967295:
		return _LockState_name_1
	default:
		return "LockState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
