// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/vogtp/go-parental-control/ent/activity"
	"github.com/vogtp/go-parental-control/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	activityFields := schema.Activity{}.Fields()
	_ = activityFields
	// activityDescDuration is the schema descriptor for duration field.
	activityDescDuration := activityFields[1].Descriptor()
	// activity.DefaultDuration holds the default value on creation for the duration field.
	activity.DefaultDuration = activityDescDuration.Default.(int64)
}
