// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Activity is the predicate function for activity builders.
type Activity func(*sql.Selector)

// Day is the predicate function for day builders.
type Day func(*sql.Selector)
